Knp\Component\Pager\Pagination\AbstractPagination:
    exclusion_policy: all
    properties:
        items:
            expose: true
            access_type: public_method
            accessor:
                getter: getItems
            type: array
            serialized_name:
                items
        currentPageNumber:
            expose: true
            serialized_name:
                page
        numItemsPerPage:
            expose: true
            serialized_name:
                maxItems
        totalCount:
            expose: true
            serialized_name:
                totalItems